global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Host metrics
  - job_name: node
    static_configs:
      - targets: ["node-exporter-y48k448wwksc4cckwgc0s4gw:9100"]

  # Container metrics
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor-y48k448wwksc4cckwgc0s4gw:8080"]

  # Business metrics
  - job_name: splitbot
    static_configs:
      - targets: ["ng4ocswkog8cg8ogc808o4ko:3000"]
